/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#0b1326",
        "surface": "#0b1326",
        "surface-dim": "#0b1326",
        "surface-bright": "#31394d",
        "surface-container-lowest": "#060e20",
        "surface-container-low": "#131b2e",
        "surface-container": "#171f33",
        "surface-container-high": "#222a3d",
        "surface-container-highest": "#2d3449",
        "surface-variant": "#2d3449",
        "on-surface": "#dae2fd",
        "on-surface-variant": "#c4c5da",
        "on-background": "#dae2fd",
        "primary": "#bcc3ff",
        "on-primary": "#001a98",
        "primary-container": "#0231fa",
        "on-primary-container": "#c1c7ff",
        "primary-fixed": "#dfe0ff",
        "primary-fixed-dim": "#bcc3ff",
        "on-primary-fixed": "#000c60",
        "on-primary-fixed-variant": "#0027d4",
        "inverse-primary": "#2040ff",
        "secondary": "#bac5ee",
        "on-secondary": "#232f50",
        "secondary-container": "#3c486a",
        "on-secondary-container": "#acb7df",
        "secondary-fixed": "#dae2ff",
        "secondary-fixed-dim": "#bac5ee",
        "on-secondary-fixed": "#0d1a39",
        "on-secondary-fixed-variant": "#3a4667",
        "tertiary": "#d3cc00",
        "on-tertiary": "#343200",
        "tertiary-container": "#b6b000",
        "on-tertiary-container": "#444100",
        "tertiary-fixed": "#f0e800",
        "tertiary-fixed-dim": "#d2cb00",
        "on-tertiary-fixed": "#1e1c00",
        "on-tertiary-fixed-variant": "#4b4900",
        "outline": "#8e8fa3",
        "outline-variant": "#444657",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#dae2fd",
        "inverse-on-surface": "#283044",
        "surface-tint": "#bcc3ff",
      },
      fontFamily: {
        "headline": ["Epilogue", "sans-serif"],
        "body": ["Noto Serif", "serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
